### ISSUE TITLE
"zoom-to-fit" doesn't, and eventually crashes

### ISSUE THREAD

**Issue by lxkain** [lxkain/timeview#1]
It only zooms out about 50%, then the next time it goes to 100%, but eventually it gives:

```
ERROR:root:Traceback (most recent call last):
  File "/Users/kain/CloudStation/CSLU/sci/timeview/timeview/gui/viewer.py", line 614, in zoomToMatch
    self.scaleBy(mag)
  File "/Users/kain/CloudStation/CSLU/sci/timeview/timeview/gui/viewer.py", line 538, in scaleBy
    for frame in self.frames])
AssertionError
```

**Comment by lxkain** [comment]
Actually, it looks like this may not be closely tied to just zoom-to-fit.

Doing this:
1. load supplied edf file.
2. move PGG signal to panel 2
3. Do "zoom to 1:1"

results in
```
ERROR:root:Traceback (most recent call last):
  File "/Users/kain/CloudStation/CSLU/sci/timeview/timeview/gui/viewer.py", line 614, in zoomToMatch
    self.scaleBy(mag)
  File "/Users/kain/CloudStation/CSLU/sci/timeview/timeview/gui/viewer.py", line 538, in scaleBy
    for frame in self.frames])
AssertionError
```

**Comment by j9ac9k** [comment]
assert statement checking to make sure that views are aligned with the reference view is failing, question is, is the assert statement wrong (am I checking the wrong thing) or is there something else I'm not keeping track of... 

```python
            assert all([reference_view_range == frame.displayPanel.pw.main_vb.viewRange()[0]
                              for frame in self.frames])
```

**Comment by j9ac9k** [comment]
Issue was that when moves were being done, they were not being done to the reference panel; but to the selected panel.

Solution I implemented is a bit brute force-ish; forces the `apply_sync` method to be called before each translate or move operation, which would force proper selection of a reference plot, and proper connections from there on out.  Alternative method would be to check if synchronized, and if so, apply scale/translation methods to the reference plot, otherwise apply them to the selected plot.

**Comment by lxkain** [comment]
Thanks so much for excellent analysis and quick fix!
